# Generated by Django 4.0.4 on 2022-09-20 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_authenticatedprofile_user_and_more'),
        ('favorites', '0002_alter_favorite_psychologist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Favorite',
            name='authenticated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authenticad', to='users.authenticated'),
        ),
    ]
