# Generated by Django 4.0.4 on 2022-09-20 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_psychologist_date"),
        ("favorites", "0003_alter_favorite_authenticated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favorite",
            name="authenticated",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authenticated",
                to="users.authenticated",
            ),
        ),
    ]
