# Generated by Django 4.0.4 on 2022-09-22 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("psychologists", "0023_psychologist_alter_education_psychologists_and_more"),
        ("favorites", "0005_alter_favorite_authenticated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favorite",
            name="psychologist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites",
                to="psychologists.psychologist",
            ),
        ),
    ]
