# Generated by Django 4.0.4 on 2022-10-07 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("psychologists", "0024_remove_psychologist_specialization_and_more"),
        ("favorites", "0006_alter_favorite_psychologist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="favorite",
            name="authenticated",
        ),
        migrations.AddField(
            model_name="favorite",
            name="user",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="psychologist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites_psychologist",
                to="psychologists.psychologist",
            ),
        ),
    ]
