# Generated by Django 4.0.4 on 2022-06-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psychologists", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="psychologist",
            name="additional_data",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="psychologist",
            name="city",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="psychologist",
            name="date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="psychologist",
            name="education",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="psychologist",
            name="email",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="psychologist",
            name="gender",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="psychologist",
            name="gender_perspective",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="psychologist",
            name="institution",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="psychologist",
            name="invoice",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="psychologist",
            name="name_2",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="psychologist",
            name="online",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="psychologist",
            name="phone_number",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="psychologist",
            name="prepaid",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="psychologist",
            name="prepaid_type",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="psychologist",
            name="province",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="psychologist",
            name="registration_number",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="psychologist",
            name="registration_type",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="psychologist",
            name="session_languages",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="psychologist",
            name="sign_language",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="psychologist",
            name="social_networks",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="psychologist",
            name="specialization",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="psychologist",
            name="team",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="psychologist",
            name="therapeutic_model",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="psychologist",
            name="work_modality",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="psychologist",
            name="work_population",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="psychologist",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="psychologist",
            name="name",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
