# Generated by Django 4.0.4 on 2022-06-09 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psychologists', '0004_specialization_psychologistid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='psychologistId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='psychologists.psychologist'),
        ),
    ]
