# Generated by Django 4.0.4 on 2022-06-09 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychologists', '0005_alter_specialization_psychologistid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialization',
            old_name='psychologistId',
            new_name='psychologist_id',
        ),
    ]
