# Generated by Django 4.0.4 on 2022-06-28 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psychologists", "0008_remove_specialization_psychologist_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TherapeuticModel",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("therapeutic_model", models.CharField(default="", max_length=1000)),
                (
                    "psychologists",
                    models.ManyToManyField(
                        related_name="therapeutic_models",
                        to="psychologists.psychologist",
                    ),
                ),
            ],
        ),
    ]
