# Generated by Django 4.0.4 on 2022-07-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologists', '0015_workmodality_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologist',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
