# Generated by Django 4.0.4 on 2022-08-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psychologists", "0016_psychologist_liked"),
    ]

    operations = [
        migrations.AddField(
            model_name="province",
            name="slug",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
