# Generated by Django 4.0.4 on 2022-07-25 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('psychologists', '0016_psychologist_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psychologist',
            name='liked',
        ),
        migrations.CreateModel(
            name='Liked',
            fields=[
                ('psychologist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='psychologists.psychologist')),
                ('liked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
