# Generated by Django 4.0.4 on 2022-08-31 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologists', '0017_province_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologist',
            name='date',
            field=models.DateField(),
        ),
    ]
