# Generated by Django 4.0.4 on 2022-09-14 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("psychologists", "0019_alter_psychologist_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prepaid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("has_prepaid", models.CharField(default="", max_length=1000)),
                (
                    "psychologists",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prepaids",
                        to="psychologists.psychologist",
                    ),
                ),
            ],
        ),
    ]
