# Generated by Django 4.0.4 on 2022-10-10 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psychologists', '0025_remove_psychologist_province_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psychologist',
            name='education',
        ),
        migrations.RemoveField(
            model_name='psychologist',
            name='gender_identity',
        ),
        migrations.RemoveField(
            model_name='psychologist',
            name='gender_perspective',
        ),
        migrations.RemoveField(
            model_name='psychologist',
            name='prepaid',
        ),
        migrations.AlterField(
            model_name='education',
            name='psychologists',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='psychologists.psychologist'),
        ),
        migrations.AlterField(
            model_name='genderidentity',
            name='psychologists',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gender_identity', to='psychologists.psychologist'),
        ),
        migrations.AlterField(
            model_name='genderperspective',
            name='psychologists',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gender_perspective', to='psychologists.psychologist'),
        ),
        migrations.AlterField(
            model_name='prepaid',
            name='psychologists',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepaid', to='psychologists.psychologist'),
        ),
    ]
