DOCTORATE = "DOCTORATE"
LICENSURE = "LICENSURE"
MASTER = "MASTER"
SPECIALIZATION = "SPECIALIZATION"

EDUCATIONS = [
    (DOCTORATE, "Doctorado"),
    (LICENSURE, "Licenciatura"),
    (MASTER, "Maestría"),
    (SPECIALIZATION, "Especialización"),
]
