# Generated by Django 4.0.4 on 2022-09-20 02:18

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_authenticated'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticatedProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authenticated_id', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PsychologistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psychologist_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('name', models.CharField(default='', max_length=1000)),
                ('gender_identity', models.CharField(default='', max_length=1000)),
                ('registration_type', models.CharField(default='', max_length=1000)),
                ('registration_number', models.CharField(default='', max_length=1000)),
                ('institution', models.CharField(default='', max_length=1000)),
                ('team', models.CharField(default='', max_length=1000)),
                ('province', models.CharField(default='', max_length=1000)),
                ('city', models.CharField(default='', max_length=1000)),
                ('education', models.CharField(default='', max_length=1000)),
                ('therapeutic_model', models.CharField(default='', max_length=1000)),
                ('gender_perspective', models.CharField(default='', max_length=1000)),
                ('specialization', models.CharField(default='', max_length=1000)),
                ('work_population', models.CharField(default='', max_length=1000)),
                ('work_modality', models.CharField(default='', max_length=1000)),
                ('online', models.CharField(default='', max_length=1000)),
                ('prepaid', models.CharField(default='', max_length=1000)),
                ('prepaid_type', models.CharField(default='', max_length=1000)),
                ('invoice', models.CharField(default='', max_length=1000)),
                ('sign_language', models.CharField(default='', max_length=1000)),
                ('session_languages', models.CharField(default='', max_length=1000)),
                ('social_networks', models.CharField(default='', max_length=1000)),
                ('phone_number', models.CharField(default='', max_length=1000)),
                ('additional_data', models.CharField(default='', max_length=1000)),
                ('name_2', models.CharField(default='', max_length=1000)),
                ('liked', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='users',
        ),
        migrations.CreateModel(
            name='Psychologist',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('psychologist', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='Suggestion',
        ),
    ]
