# Generated by Django 4.0.4 on 2022-09-20 03:05

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_authenticatedprofile_psychologistprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psychologistprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Psychologist',
        ),
        migrations.CreateModel(
            name='Psychologist',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date', models.DateField()),
                ('name', models.CharField(default='', max_length=1000)),
                ('gender_identity', models.CharField(default='', max_length=1000)),
                ('registration_type', models.CharField(default='', max_length=1000)),
                ('registration_number', models.CharField(default='', max_length=1000)),
                ('institution', models.CharField(default='', max_length=1000)),
                ('team', models.CharField(default='', max_length=1000)),
                ('province', models.CharField(default='', max_length=1000)),
                ('city', models.CharField(default='', max_length=1000)),
                ('education', models.CharField(default='', max_length=1000)),
                ('therapeutic_model', models.CharField(default='', max_length=1000)),
                ('gender_perspective', models.CharField(default='', max_length=1000)),
                ('specialization', models.CharField(default='', max_length=1000)),
                ('work_population', models.CharField(default='', max_length=1000)),
                ('work_modality', models.CharField(default='', max_length=1000)),
                ('online', models.CharField(default='', max_length=1000)),
                ('prepaid', models.CharField(default='', max_length=1000)),
                ('prepaid_type', models.CharField(default='', max_length=1000)),
                ('invoice', models.CharField(default='', max_length=1000)),
                ('sign_language', models.CharField(default='', max_length=1000)),
                ('session_languages', models.CharField(default='', max_length=1000)),
                ('social_networks', models.CharField(default='', max_length=1000)),
                ('phone_number', models.CharField(default='', max_length=1000)),
                ('additional_data', models.CharField(default='', max_length=1000)),
                ('name_2', models.CharField(default='', max_length=1000)),
                ('liked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.DeleteModel(
            name='PsychologistProfile',
        ),
    ]
