# Generated by Django 4.0.4 on 2022-09-20 03:11

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_psychologistprofile_user_delete_psychologist_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="authenticatedprofile",
            name="user",
        ),
        migrations.DeleteModel(
            name="Authenticated",
        ),
        migrations.CreateModel(
            name="Authenticated",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("users.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.DeleteModel(
            name="AuthenticatedProfile",
        ),
    ]
