# Generated by Django 4.0.4 on 2022-09-20 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_authenticatedprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologist',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
