name: Update Script
on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:
jobs:
  update_script:
    name: Update script with GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update CSV
        run: python3 -c 'from seeder.utils import update_csv; update_csv()'

      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v11
        id: verify-changed-files
        with:
          files: |
            seeder/psychologists.csv

      - name: Run step only when files change.
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          echo "Changed files: ${{ steps.verify-changed-files.outputs.changed_files }}"

      - if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          justlogin: true

      - if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: heroku auth:whoami

      - name: Setup Python
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Run Script and Update
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: heroku run --app ${{ secrets.HEROKU_APP_NAME }} PYTHONPATH=./ python3 seeder/main.py

      - name: Commit and Push Changes
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Updated script on `date` with GitHub Actions"
          git push origin main
