name: Update Script
on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:
jobs:
  update_script:
    name: Update script with GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Login to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          justlogin: true

      - name: Add Heroku remote
        run: heroku git:remote --app=${{ env.HEROKU_APP_NAME }}

      - name: Run Script and Update
        env:
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
          EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
          RECIPIENT_ADDRESS: ${{ secrets.RECIPIENT_ADDRESS }}
        run: |
          heroku run python3 seed.py

      # - name: Commit and Push Changes
      #   run: |
      #     git config --local user.email "actions@github.com"
      #     git config --local user.name "GitHub Actions"
      #     git add .
      #     git commit -m "Updated script on `date` with GitHub Actions"
      #     git push origin master
